version: '3.4'

services:
  lemans_db:
    image: postgres:latest
    networks:
      - lemansdb
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=pass
  lemansapi:
    image: ${DOCKER_REGISTRY-}lemansapi
    networks:
      - api
      - lemansdb
    expose:
      - "8081"
      - "8080"
    depends_on:
      - "lemans_db"
    build:
      context: .
      dockerfile: LeMansAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=lemans_db;Port=5432;Database=LeMansDb;Password=pass;User Id=postgres;Include Error Detail=true;
  users_db:
    image: postgres:latest
    networks:
      - usersdb
    expose:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=pass
  lemansapp:
    image: ${DOCKER_REGISTRY-}lemansapp
    networks:
      - usersdb
      - api
    depends_on:
      - "lemansapi"
      - "users_db"
    build:
      context: .
      dockerfile: LeMansApp/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=users_db;Port=5432;Database=UsersDb;Password=pass;User Id=postgres;Include Error Detail=true;
      - ApiConfig__Url=http://lemansapi:8080/
networks:
  usersdb:
    driver: bridge
  lemansdb:
    driver: bridge
  api:
    driver: bridge

